// This file provides a pre-defined list of movie genres
export const MOVIE_GENRES = [
  "Action",
  "Adventure",
  "Animation",
  "Anime",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "Horror",
  "Music",
  "Musical",
  "Lifestyle",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Seasonal",
  "Short",
  "Sport",
  "Thriller",
  "War",
  "Western"
]